### PR TITLE
not sure hmm :(

### PR DESCRIPTION
**Pull request by helloitsbilly**

### CODE REVIEW

**Comment by helloitsbilly** [comment]
lmao i forgot to make a way for the *Discord.Submit.Visible = true* to work

**Comment by helloitsbilly** [comment]
you probably wont use this code its actually shit

**Comment by helloitsbilly** [comment]
> local HB=game:GetService"RunService".RenderStepped

Also im not sure what "HB:Wait()" is used for and if its actually needed in this code

**Comment by jotslo** [comment]
Your pull request has been merged, thank you very much for your contribution this repository!

**Pull request merged**
